name: Markdown Lint & Spell Check

on:
  pull_request:
    branches:
      - main

jobs:
  markdown-lint:
    name: Run Markdown Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md' --ignore node_modules

  spell-check:
    name: Run Spell Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run spell checker
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: '.cspell.json'
          files: '**/*.md'
          inline: true
